id: A198FDD09
title: A Concise Recitation of the Preliminary Practice according to the New Treasure
  of Dudjom
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:50:23.087270
  last_modified_at: 2022-03-01 04:50:23.087278
