id: A198FDD09
title: 'Illuminating the Path to Liberation: A Preliminary Practice (Ngöndro)'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:50:23.091998
  last_modified_at: 2022-03-01 04:50:23.092003
