id: A198FDD09
title: The Concise Mahāmudrā Preliminaries Arranged for Recitation
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:50:23.094050
  last_modified_at: 2022-03-01 04:50:23.094056
