id: A198FDD09
title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice of Longchen
  Nyingtik'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:50:23.099008
  last_modified_at: 2022-03-01 04:50:23.099011
