id: A198FDD09
title: Guru Yoga
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:50:23.090318
  last_modified_at: 2022-03-01 04:50:23.090323
