id: A198FDD09
title: 'The Excellent Path to Enlightenment: A Brief Practice of the Preliminaries'
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:50:23.096170
  last_modified_at: 2022-03-01 04:50:23.096174
